### ISSUE TITLE
Start using Gitian for builds

### ISSUE THREAD

**Issue by Gnos1s** [Anoncoin/oldrepo-backup#38]
We should really be using the Gitian deterministic build system for all the binaries we publish. This is mostly a to-do note to myself for when I have some time to work on it, but anybody is welcome to help if they can :)

https://gitian.org/
https://github.com/devrandom/gitian-builder

**Comment by GroundRod** [comment]
I was and still would consider it Gnos1s, however with the new 'depends' toolchain builder, I don't need it to build cross-platform or otherwise.  So going to pass on keeping the files updated or usable for anoncoin, it's too complex a system to setup and hard to get working for any coin other than bitcoin.  If we can figure out how to build with consenses, using the new 'depends' toolchain builder, which is very close to being determinstic, then we can have a wider range of developers added to our list of folks willing to sign off on any paticular build.  Other than that one reason, I'm not interested in making a career out of getting gitian-builder to work and keep it working with the latest anoncoin builds...

GR
