### ISSUE TITLE
Linux nightly builds - shared library libdb_cxx-5.1.so

### ISSUE THREAD

**Issue by lunokhod** [Anoncoin/oldrepo-backup#42]
Here is a problem from matthewh3 on BCT: 

> Which of the following nightly builds do I need for Xubunty 14.04LTS - ?> https://nightly.privacysolutions.no/Anoncoin-Linux - I got the top one build 100 and get the following error 
> 
> ./anoncoin-qt: error while loading shared libraries: libdb_cxx-5.1.so: cannot open shared object file: No such file or directory
> 
> I've installed libudev-dev

**Comment by Gnos1s** [comment]
Berkeley DB 5.x should not be used, as it causes compatibility problems for wallet.dat files generated using Berkeley DB 4.x. Just about everyone uses 4.x.

**Comment by yhaenggi** [comment]
correct. unfortunately meeh donst want to link against 4.x. i warned him about the problems.

**Comment by GroundRod** [comment]
As long as we release builds now, that are linked with the pre-build toolchain library, this issue is over, no matter what the user has installed on his/her system.  If they build and use a wallet.dat based on db v5.1, well they are on there own....I would suggest they transfer any funds out of that wallet.dat file build, and install the new software, then transfer the funds back into it.

For most people though...they will have a wallet.dat file like mine, it came from a windows 32 bit system running Anoncoin v0.8.5.6, it works fine with our newest V9 builds.

We may have allot of folks that need to upgrade their old client wallet.dat file to the new program, they can now easily do that with their old wallet.dat files, even with funds in it.

We need some instructions on how they can do that though, like backup first then ..didadida.. and start Anoncoind or Anoncoin-qt with the command line options -rescan and isn't there an upgrade wallet parameter or command too.... that should be explained.

At least the DB version we build with, on all platforms, is version 4.8, and should be correct for most people, or an easy upgrade would not be so simple.

Think this issue can then be closed, unless any of you disagree....

**Comment by yhaenggi** [comment]
agree
