### ISSUE TITLE
Notes on the GUI

### ISSUE THREAD

**Issue by lunokhod** [Anoncoin/oldrepo-backup#67]
I have a couple comments on the GUI.
1. Would it be possible to make the Qt menu bar (overview, send, receive, transactions) to be on the left hand side by default (as opposed to the top), as in the following image?

https://img.bi/#/m8Cjhlq!OyUbDIOhUQuj1KLiOiia76uaTBLHr4vDkMzsycxJ
1. When placing the menu bar on the left, the four icons are "centered". In this mode, they should be aligned to the left.
2. Would it be possible to add two additional items to the menu bar? "Receiving addresses" and "Sending addresses". As it is now these are pop-up windows that are only accessible from the main OS menu bar (see above image) but it would be more practical to have these as windows of the Qt wallet (like overview, send, receive and transactions). In fact, this is how it used to be with the 0.8.6 wallet. It might be possible to combine these into a single "Address book", but I am not sure of the best way to do this.

I will try to work on this myself, but this might take a really long time, so any help/suggestions would be appreciated.

**Comment by GroundRod** [comment]
Interesting ideas.  Please do go ahead and work on them if your able.  Some I really like, and would love to work on too, but I'm at least 200hrs away from getting any of these code changes made, perhaps much more.  Many I would prefer to delay for what is to me, a very good reason, getting what is 'under the hood' working well first.  

Then secondly get our Anoncoin complete build environment upgraded to the v10 level.  If changes like this are to be made in QT, it will be a great deal harder to EVER do that.  What would have been a job I can do piece meal, as required and when synchronized with other data structure and variable changes, will become a 4 day job, and I'll still not have the original problem I was trying to fix solved.

I can't fully implement some of the new ideas introduced by v10, until that upgrade work has been finished, many bug fixes too.  The standard QT needs to upgrade with it, to support those new data structures and test that they are working.  So I'm only going to fix the problems already created by adding and changing stuff in QT, removing the bad idea i2poptions, and little things you've asked for, that is about it.  Much of the work I'm doing has very little to do with QT, as that is but one of the output programs we cross-platform build and target for distribution as binaries.  

Its critical to my code/build/test cycle right now, that changes like this are NOT made.  Down the road, and after the engine is running right, I'm all for ripping QT up and building a better interface.  If you or another team have that going already, I'm all for it.

So as I see it, we have a couple of alternatives here.  

Option #1
This is worked on as a separate program, handled in a separate branch and outside of the Anoncoin Core.   Simply clone the 'develop' branch whenever you want to start working on it.  Hopefully at some later date it can be merged back in as the QT replacement.  As the rest of the build system moves forward, it will be up to you to keep pace with the 'under the hood' changes going on, I have no intention of leaving the source code at the v0.9.3 level, just so QT still works, I use a specific methodology that requires my changes happen all together, and as needed, inside and out of the standard QT client we pretty much have now.

Option #2
We try to keep the changes coming in to our 'develop' branch and ensure constantly that it continues to build and work well for all the different platforms we support.

This will mean when its not working, then it impacts my ability to get anything else done.   I'm no QT expert, so when that happens, it's problems have now become mine.  

As a case in point, just last night after more than 2 hours trying to get REGTEST and TESTNET working I called it a night, partially because of being side tracked with a new problem.  One small change made in guiconstants.h renaming the QT Application from Anoncoin-Qt to Anoncoin, caused all the hidden QT .config files to also be renamed, so I had six copies in my working directory and was stumped as to which was being used now, took awhile to figure out why and where.  Regarding that point, for systems that are case insensitive to filenames, having two hidden configuration files that differ only by the fact one starts with a capital 'A' and the other by a lowercase, is a bad idea.  Our primary one being the anoncoin.conf file in the data directory is not this same QT file configuration file by that name.   A very bad change IMO.  I reverted that one, and the other one in the src/qt/test directory, but left the Mac build changes alone.

So please, if your able and willing to work on this great.  But do so without committing those changes to the 'develop' branch at this time.

I'll be sending a commit up here in a few minutes, should have everything except TESTNET working for a hardfork build....

Thanks,
GR

**Comment by GroundRod** [comment]
Think I figured out a Third option...

We can have at least the initial setup done by me in a matter of a few hours.

This keeps everything in Anoncoin Core and the 'develop' branch.  We will start building a new qtanc5 (or what ever you want to call it, referenced below as QT2), a copy of all that is in src/qt now, 99.9% of everything that makes Anoncoin-Qt what it is for a look and feel interface.

It can easily be made to build along side src/qt with all its associated subfolders, as a starting point, you will have the initial translations, forms and other resources all working and linking together to form an new executable.  Change and reorganize however you want to!

Will do this right after i finish removing the i2poptions dialog, as it need to be gone yesterday....

This way, I can have my src/qt/ as is and work on as I need to.  Yet new development work on a QT2 can diverge into a different direction.  If it turns out I can not compile/link QT2, there will be one line of code I comment out, until the problems are resolved.  Attempts to build it will not be a problem for any of the rest of us that build the new software regularly.

Will fire up the i2prouter and be available on the anoncoin-dev irc chat later tonight and over the weekend some,  need to address this and the pending hardfork code testing we will be able to start....

l8r
GR

**Comment by lunokhod** [comment]
GR, don't worry about this now. It's not a priority, and it will take a couple weeks for me to work on this anyways...

**Comment by GroundRod** [comment]
Sounds good, keep the ideas coming in then, for when we can be put work into this.  You've for sure got some great ideas about what direction we should take to have a better look & feel.

Still very much considering my options on spinning off a separate & new executable build subdirectory, one for the new interface design to take place in, and keep the old src/qt directory as just a reference base build, something to work on when the other sections of code need updating too....after testing, if any of it is useful, the changes can be ported into the new and  official QT client build subdirectory, which hopefully by then, we are releasing as the official binary for an Anoncoin QT client....

**Comment by Cryptoslave** [comment]
I agree with this good idea to test change in GUI
